project:
  type: website

website:
  title: "InfoViz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format: revealjs
  # html:
  #   theme: cosmo
  #   css: styles.css
  #   toc: true



